v0.5.0
Chicago/lead-safe-api-docs pull request #20
Opened 2018-01-03 22:01 UTC by tomschenkjr

API
  * API documentation specifies an `error` field which provides any error messages from the request. (#17, #14)
  * Error codes follow HTTP status code conventions

Application Form
  * Added application page that allows list of eligible hospitals to select and apply #2
  * Added required fields needed to apply (from both the clinical and technical point-of-contact)
 
Clinical Content
  * Added FAQ section in both Spanish and English #16
  * Provided PDF download of both Spanish and English FAQ
  * Added a downloadable map of where elevated blood-lead levels exist throughout Chicago. #16

_After reviews have approved this request, I will only merge the request when we've pushed v0.5.0 into production._

2018-01-03 22:03 UTC, tomschenkjr commented
@RaedMan - Please review the [terms of service](https://github.com/Chicago/lead-safe-api-docs/blob/ebd0f539efbe1add06d4d5c8b15b35d177f82f8b/docs/tos.md) again for any issues.

There is one obvious sentence that needs clarifying:

> The risk score, defined as (XXXXXXXXXXX) will be sent to health centers through electronic health records (EHR) and physicians will have the opportunity[...]

however, we will fix that when we release v0.6.0 of the API.

2018-01-10 15:32 UTC, geneorama commented
I noticed a broken link in the notes of the main page, the https is missing the "h"

```
[^1]: Potash _et al._ (2015) [Predictive Modeling for Public Health](ttps://dssg.uchicago.edu/wp-content/uploads/2016/01/p2039-potash.pdf). _Proceedings of the 21th ACM SIGKDD International Conference on Knowledge Discovery and Data Mining_ pp. 2039-2047.
```

should be 
```
[^1]: Potash _et al._ (2015) [Predictive Modeling for Public Health](https://dssg.uchicago.edu/wp-content/uploads/2016/01/p2039-potash.pdf). _Proceedings of the 21th ACM SIGKDD International Conference on Knowledge Discovery and Data Mining_ pp. 2039-2047.
```

2018-01-10 15:35 UTC, geneorama commented
Talked to @tomschenkjr and sounds like @RaedMan is working on the eligibility form, but for now the link is blank in the Eligibility section.  Do we want to put in note that it's under construction or take the link out for now? 

Also I didn't see an open issue for this or a note in the wiki.  This seems like a big task, I'm wondering if I missed it in the milestones.

2018-01-10 16:44 UTC, geneorama approved these changes
I made a few minor changes and committed them to dev.

2018-01-10 16:57 UTC, RaedMan reviewed
Not sure where to add this in TOS:  

"The use of the API precludes healthcare provider(s) and all staff, including third-party contractors, from the healthcare facility from transferring data or publishing any results derived from its activities hereunder and will not disclose any results or other material based upon data provided by the City without written permission from the City."

This may need some editing.

2018-01-10 19:08 UTC, geneorama requested changes

2018-01-10 19:08 UTC, geneorama commented on docs/tos.md
> +Though lead is no longer used in paint, plumbing, gasoline and a myriad of other products in the United States, Chicago’s older housing stock creates a persistent problem as homes built prior to 1978
This is good information, but should it be part of the TOS?

2018-01-10 19:08 UTC, geneorama commented on docs/tos.md
> +This lead safe predictive model helps identify infants at risk of being lead poisoned in homes with lead paint. The model provides an opportunity to prevent lead paint exposure through high priority
I'm not sure if we should have "background" in the terms of service, but wherever this content lands I propose that we use the terminology "infants and fetuses" here to make subsequent language easier. In the next paragraph we refer to "pregnant patients", which is confusing and perhaps technically incorrect.

2018-01-10 19:08 UTC, geneorama commented on docs/tos.md
> +The risk score, defined as (XXXXXXXXXXX) will be sent to health centers through electronic health records (EHR) and physicians will have the opportunity to be alerted to either order a blood lead tes
The [risk score](https://github.com/Chicago/lead-safe-api-docs/issues/21) is part of the v0.6 milestone, but how do we want to describe the risk score here?  

Also, I don't understand why we're saying that "physicians will have the opportunity to be alerted to either...". Will they be opting into the alerts?

In any event, I think the risk score documentation should be separate from the description of alerts, and I'm not sure that the risk score documentation belongs in the TOS.

2018-01-10 19:08 UTC, geneorama commented on docs/tos.md
> +Access to the XXXXXX Environment is subject to Your compliance with these terms as well as development of a privacy policy, including clear and conspicuous disclosure to users of any practice whereby
I'm not sure what the XXXXXX Environment means, so I'm not sure how to propose better terminology.

2018-01-10 20:58 UTC, tomschenkjr commented on docs/tos.md
> +Though lead is no longer used in paint, plumbing, gasoline and a myriad of other products in the United States, Chicago’s older housing stock creates a persistent problem as homes built prior to 1978
Since it was provided by CDPH, let's keep it unless they prefer to have different language.

2018-01-10 20:58 UTC, tomschenkjr commented on docs/tos.md
> +This lead safe predictive model helps identify infants at risk of being lead poisoned in homes with lead paint. The model provides an opportunity to prevent lead paint exposure through high priority
Likewise, to the above, we'll keep it unless CDPH wants something different.

2018-01-10 21:00 UTC, tomschenkjr commented on docs/tos.md
> +The risk score, defined as (XXXXXXXXXXX) will be sent to health centers through electronic health records (EHR) and physicians will have the opportunity to be alerted to either order a blood lead tes
Yes, they will be provided information/alert/scores so the physician can order blood tests/visual inspections.

2018-01-10 21:00 UTC, tomschenkjr commented on docs/tos.md
> +Access to the XXXXXX Environment is subject to Your compliance with these terms as well as development of a privacy policy, including clear and conspicuous disclosure to users of any practice whereby
Placeholder for the name of the application. Will be "Lead Safe". Will make it in the next release.

2018-01-10 21:07 UTC, tomschenkjr commented
@RaedMan - I've included the language under the "[City Policies and Requirements Regarding Use of API Services](https://github.com/Chicago/lead-safe-api-docs/blob/09b0acb835db71d49f8f881dac6c5019d5a1993e/docs/tos.md#city-policies-and-requirements-regarding-use-of-api-services)".

Let me know your thoughts.

2018-01-10 21:49 UTC, geneorama approved these changes

2018-01-10 21:49 UTC, geneorama commented
@tomschenkjr thanks for the clarifications about what's going into .5 vs .6.  This is good for .5.

2018-01-11 20:42 UTC, merged

2018-01-11 20:42 UTC, tomschenkjr commented
v0.5.0 has been deployed to the production servers! I am merging this code.

I will be sending an email to health partners so they can conduct some testing.

@RaedMan - the new web-based documentation will be updated as well. You can show the Lead Safe documentation to team members, which they can view in browsers: https://chicago.github.io/lead-safe-api-docs/

2018-01-11 21:00 UTC, geneorama commented
So far all the tests are passing (including expected errors), except for QA because there's a problem with the actual server.  George has opened a ticket with EKI on that.